---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: source/_posts/opini
  label: postingan opini
  create: all
  match: "**/*"
- type: directory
  path: source/_posts/program-kerja
  label: Postingan program kerja
  create: all
  match: "**/*"
- type: directory
  path: content/pages
  label: Pages
  create: all
  match: "**/*"
upload_dir: Polri Presisi
public_path: https://res.cloudinary.com/bimagv/image/upload
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:, :month:, :day:,:filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
